// FIXME
export const DEV_MAIN_BOARD_VIEW = 'DEV_MAIN_BOARD_VIEW'
export const SETTING_GROUP_VIEW = 'SETTING_GROUP_VIEW'
export const STATE_GROUP_VIEW = 'STATE_GROUP_VIEW'
export const CONTROL_GROUP_VIEW = 'CONTROL_GROUP_VIEW'
export const RECORD_GROUP_VIEW = 'RECORD_GROUP_VIEW'
export const REPORT_GROUP_VIEW = 'REPORT_GROUP_VIEW'
export const EVENT_INFO_GROUP_VIEW = 'EVENT_INFO_GROUP_VIEW'
export const LCD_MENU_VIEW = 'LCD_MENU_VIEW'
export const WAVE_CONFIG_VIEW = 'WAVE_CONFIG_VIEW'
export const WAVE_GROUP_VIEW = 'WAVE_GROUP_VIEW'
export const GRAPH_EDITOR_VIEW = 'GRAPH_EDITOR_VIEW'
export const CLASS_VIEW_MAP = {
  MainBoardConfig: DEV_MAIN_BOARD_VIEW,
  Page: GRAPH_EDITOR_VIEW,
  SettingGroup: SETTING_GROUP_VIEW,
  StateGroup: STATE_GROUP_VIEW,
  ControlGroup: CONTROL_GROUP_VIEW,
  RecordGroup: RECORD_GROUP_VIEW,
  ReportGroup: REPORT_GROUP_VIEW,
  EventInfoGroup: EVENT_INFO_GROUP_VIEW,
  WaveInst: WAVE_CONFIG_VIEW,
  WaveGroup: WAVE_GROUP_VIEW,
  LcdMenuConfig: LCD_MENU_VIEW
}
